// Auto-generated by generate_data.py — do not edit by hand.
// To update, edit Students Details.xlsx and/or the GROUP_SCHEDULE
// in generate_data.py, then re-run: python generate_data.py

const INSTITUTION_NAME = "MIT Vishwaprayaag University Solapur";

const STUDENTS = [
  {
    "prn": "SCFU124088",
    "name": "Priyanka Sahajrao",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125071",
    "name": "Shaikh Izhan Samirahmad",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125072",
    "name": "Mali Sarang Sunil",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125073",
    "name": "Kore Lakshya Vijaykumar",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125074",
    "name": "Shrawasti Vijay Dhole",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125075",
    "name": "Gaikwad Sanjana Samadhan",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125076",
    "name": "Nadaf Rehan Ahmed Dawal",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125078",
    "name": "Mohammed Rehan Imran Shai",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125079",
    "name": "Khandelwal Tanmay Mahesh",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125080",
    "name": "Shaikh Yashfiya Amjadhusa",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125081",
    "name": "Waychal Vedant Praveen",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125082",
    "name": "Madiha Abdul Vahab Maniya",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125083",
    "name": "Pawar Nikhil Pramod",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125084",
    "name": "Ayachit Prerana Anand",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125085",
    "name": "Onkar Birajdar",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125086",
    "name": "Narwate Arjun Dhondiram",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125087",
    "name": "Bhadre Shashwat Dhanappa",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125088",
    "name": "Shaikh Shahnawaz Riyaz Ah",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125089",
    "name": "Nadaf Sumaiyya Ismail",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125090",
    "name": "Kurude Piyush Dayanand",
    "program": "B.Tech CSE",
    "group": "G1"
  },
  {
    "prn": "SCFU125091",
    "name": "Ronit Kumar Dalai",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCFU125092",
    "name": "Jadhav Sarthak Sachin",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCFU125093",
    "name": "Patil Shrisha Pramod",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCFU125094",
    "name": "Shinde Rohit Madhav",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCFU125095",
    "name": "Omkar Kalshetti",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCFU125096",
    "name": "Farkande Zakwan Akil",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCFU125097",
    "name": "Vishwanth Choudhari",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCFU125098",
    "name": "Sayyed Saniya Mehraj Jame",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCFU125099",
    "name": "Battu Rohan Rajesh",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCFU125100",
    "name": "Om Kashid",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCFU125101",
    "name": "Khakre Megha Vikas",
    "program": "B.Tech CSE",
    "group": "G2"
  },
  {
    "prn": "SCLU325001",
    "name": "Harshit Ranbhare",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G2"
  },
  {
    "prn": "SCLU325002",
    "name": "Kshitij Vinod Gambhire",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G2"
  },
  {
    "prn": "SCLU325003",
    "name": "Sachin Shekappa Teggelli",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G2"
  },
  {
    "prn": "SCLU325004",
    "name": "Om Bhosale",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G2"
  },
  {
    "prn": "SCLU325005",
    "name": "Snehal Kashinath Kalburgi",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G2"
  },
  {
    "prn": "SCLU325006",
    "name": "Chinmay Fadtare",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G2"
  },
  {
    "prn": "SCLU325007",
    "name": "Abhinav surpurkar",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G2"
  },
  {
    "prn": "SCLU325008",
    "name": "Pragati Prakash Nagarkar",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G2"
  },
  {
    "prn": "SCLU325009",
    "name": "Om bamgonda",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G2"
  },
  {
    "prn": "SCLU325010",
    "name": "Parinita Ganesh Gurram",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325011",
    "name": "Nitin Mali",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325012",
    "name": "Hasini .S. kodam",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325013",
    "name": "Om Swami",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325014",
    "name": "Sayma Sayyad",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325015",
    "name": "Sohail Nadaf",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325016",
    "name": "Mohammed Gause Darbarwala",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325017",
    "name": "Manthan Patil",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325018",
    "name": "Nandini chakral",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325019",
    "name": "vaibhav",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325020",
    "name": "Samarth Nitin Malwadkar",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325021",
    "name": "Harshvrdhan Sirsat",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325022",
    "name": "Mrunali Adam",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325023",
    "name": "Ajinkya Jalindar Shete",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325024",
    "name": "Aryan Archit Chavan",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325026",
    "name": "amol lange",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325027",
    "name": "Pranita Prashant Jadhav",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325028",
    "name": "Varad Suraj Patil",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325029",
    "name": "M Sadique Kampli",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325030",
    "name": "Vaibhavi Kumbhare",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G3"
  },
  {
    "prn": "SCLU325031",
    "name": "BABBUR SIDHARTHA PRASAD",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325032",
    "name": "Bhumika Sanga",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325033",
    "name": "Rajnandini Sapate",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325034",
    "name": "AKASH NARENAVAR",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325035",
    "name": "Sairaj Mane",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325036",
    "name": "Onkar Prashant khatake",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325037",
    "name": "Nupur Salunke",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325038",
    "name": "Venkatvinay Desaboyina",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325039",
    "name": "Ajinkya Supate",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325040",
    "name": "Mrunalini Sandeep Bhadange",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325041",
    "name": "Sanket Balasaheb Mengale",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325042",
    "name": "Onkar baliram Thite",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325043",
    "name": "Isha Mhamane",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325044",
    "name": "Rushiprasad Raju Chimman",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325046",
    "name": "Abhishek Raut",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325047",
    "name": "Rohit Pramod Gore",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCLU325048",
    "name": "Samruddhi Vishwendra More",
    "program": "B.Tech IT (Lateral Entry)",
    "group": "G4"
  },
  {
    "prn": "SCFU425061",
    "name": "Koli Snehal Ganesh",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425062",
    "name": "Shinde Aditya Santosh",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425038",
    "name": "Navale Vedantraj Chandra",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425041",
    "name": "Balgaonkar Arjun Vilas",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425056",
    "name": "Satkhed Rida Feroze",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425024",
    "name": "Anand Nagesh Salunke",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425001",
    "name": "Subham Dey",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425066",
    "name": "Balingal Lochana Mallikar",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425035",
    "name": "Bhadule Sudarshan Sadanan",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425044",
    "name": "Priti Gundu Dalavi",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425046",
    "name": "Gade Piyush Ketan",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425047",
    "name": "Khule Aditi Yuvraj",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425005",
    "name": "Bhinge Onkar Pandurang",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425034",
    "name": "Jadhav Aaryal Chandrakant",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425065",
    "name": "Onkar Masaji Patil",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425039",
    "name": "Akude Raj Narasinha",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425028",
    "name": "Sudarshan Kanip Dade",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425049",
    "name": "Chityal Sagar Suryakant",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425063",
    "name": "Gajjam Pushkar Jayant",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425054",
    "name": "Terdal Shambhavi Sadashiv",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425058",
    "name": "Dange Rafa Mudassar",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425020",
    "name": "Subhedar Gafur Abdul",
    "program": "B.Tech AIML",
    "group": "G4"
  },
  {
    "prn": "SCFU425027",
    "name": "Mujawar Karim Javid",
    "program": "B.Tech AIML",
    "group": "G5"
  },
  {
    "prn": "SCFU425040",
    "name": "Menthe Sharanraj Shivrudr",
    "program": "B.Tech AIML",
    "group": "G5"
  },
  {
    "prn": "SCFU425002",
    "name": "Shaikh Alina Altaf",
    "program": "B.Tech AIML",
    "group": "G5"
  },
  {
    "prn": "SCFU225001",
    "name": "Shahid Mujawar",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225002",
    "name": "Pavitra Gore",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225003",
    "name": "Maher Shaikh",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225004",
    "name": "Henal Patel",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225005",
    "name": "Omkar Devidas Gaikwad",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225006",
    "name": "Hitesh Vijay Kukreja",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225007",
    "name": "Prakash Ganesh Udhanshetti",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225009",
    "name": "Santosh Rajendra Shirkul",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225010",
    "name": "Aditya Namdeo Aldar",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225011",
    "name": "Shrikrushna Satav",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225012",
    "name": "Akash Basavaraj Godale",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225013",
    "name": "Prachi sominath Rathod",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225014",
    "name": "Sneha Houshetti",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225015",
    "name": "Tahniyat Shaikh",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225016",
    "name": "Anfus Shamsi",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225017",
    "name": "Abubakr Zamindar",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225018",
    "name": "Maroti Hajgule",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225019",
    "name": "Nikhil Nitin Kurle",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225020",
    "name": "Kadir Sagari",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225021",
    "name": "Rehan Mulani",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225022",
    "name": "Manjiri Shinde",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225023",
    "name": "Mukund Mundada",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225024",
    "name": "Hiresh Chandrakant Jawanjal",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225025",
    "name": "Yuvraj Doddale",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFU225026",
    "name": "Sahil bapu shaikh",
    "program": "BCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125001",
    "name": "Arfaat Patel",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125004",
    "name": "Prajakta Ghorpade",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125007",
    "name": "Yusuf Shaikh",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125008",
    "name": "Onkar Jituri",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125010",
    "name": "Priyanka Adheli",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125011",
    "name": "Sairaj Anvekar",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125012",
    "name": "Tushar Dugane",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125013",
    "name": "Suraj Pujari",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125014",
    "name": "Jatin Kolhapure",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125015",
    "name": "Samarth Kapase",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125016",
    "name": "Mayuri Mengji",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125017",
    "name": "Pranali Koli",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125018",
    "name": "Mohamad Shaikh",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125019",
    "name": "Ganesh Sagar",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125020",
    "name": "Aniket Gaikwad",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125021",
    "name": "Sufiyan Shaikh",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125022",
    "name": "Saniya Shaikh",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125023",
    "name": "Trupti Gangavati",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125024",
    "name": "Shubranil Pandit",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125025",
    "name": "Laxmikant Patane",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125026",
    "name": "Rohan Lokhande",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125028",
    "name": "Arshiya Tamboli",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125029",
    "name": "Ajay Yangal",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125030",
    "name": "Viraj Kandikatla",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125031",
    "name": "Shrihari Gajul",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125032",
    "name": "Iram Patel",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125033",
    "name": "Swami Sakshi Balayya",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125034",
    "name": "Musa Shaikh",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125035",
    "name": "Tanmay Thorat",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125036",
    "name": "Rajnandini Dhongade",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125037",
    "name": "Anzalna Bidri",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125038",
    "name": "Chaitanya Jadhav",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP125039",
    "name": "Sujal Nalawade",
    "program": "MCA",
    "group": "G5"
  }
];

const GROUP_SCHEDULE = {
  "G1": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration",
      "location": "Room 202 (2nd Floor)"
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch Break + Registration",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Campus Tour",
      "location": ""
    }
  ],
  "G2": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration",
      "location": "Room 204 (2nd Floor)"
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch Break + Registration",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Campus Tour",
      "location": ""
    }
  ],
  "G3": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration",
      "location": "Room 219 (2nd Floor)"
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch Break + Registration",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Campus Tour",
      "location": ""
    }
  ],
  "G4": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration",
      "location": "Room 213 (2nd Floor)"
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch Break + Registration",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Cyber Security",
      "location": "Computing Auditorium"
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Campus Tour",
      "location": ""
    }
  ],
  "G5": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration",
      "location": "Room 317 (3rd Floor)"
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch Break + Registration",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    }
  ],
  "G6": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration",
      "location": "Room 304 (3rd Floor)"
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch Break + Registration",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Cyber Security",
      "location": "Computing Auditorium"
    }
  ],
  "G7": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration",
      "location": "Room 402 (4th Floor)"
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch Break + Registration",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Cyber Security",
      "location": "Computing Auditorium"
    }
  ],
  "G8": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration",
      "location": "Room 502 (5th Floor)"
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch Break + Registration",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    }
  ]
};
