// Auto-generated by generate_data.py — do not edit by hand.
// To update, edit Students Details.xlsx and/or the GROUP_SCHEDULE
// in generate_data.py, then re-run: python generate_data.py

const INSTITUTION_NAME = "MIT Vishwaprayaag University Solapur";

const STUDENTS = [
  {
    "prn": "SCFP126001",
    "name": "Perala Nikita Ramkrishana",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126002",
    "name": "Bamani Vaishnavi Pramod",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126003",
    "name": "Bodgal Akshad Kishor",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126004",
    "name": "Dhanwani Aashish Vijay",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126005",
    "name": "Chavan Tejaswini Mayur",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126006",
    "name": "Bhanage Prashant Irrappa",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126007",
    "name": "Gund Varun Sanjay",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126008",
    "name": "Daund Chetana Pramod",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126009",
    "name": "Jamadar Anjumparavez Mehaboob",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126010",
    "name": "Jigajambagi Komal Hanamant",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126011",
    "name": "Avachar Sham Shivaji",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126012",
    "name": "Patil Aditya Anmol",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126013",
    "name": "Mushan Shashank Shrikant",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126014",
    "name": "Chordiya Roshani Dhanraj",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126015",
    "name": "Mandhare Prasad Ambadas",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126016",
    "name": "Mahimkar Samarth Kashinath",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126017",
    "name": "Vagati Onkar Mahadev",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126018",
    "name": "Bitodkar Shreya Sudhir",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126019",
    "name": "Mahindrakar Snehal Manohar",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126020",
    "name": "Dhotre rutuja Chandrakant",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126021",
    "name": "Kalshetti Ambaresh Laxman",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126022",
    "name": "Survase Chetan Shrishail",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126023",
    "name": "Kulkarni Dhanshri Dattatray",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126024",
    "name": "Moholkar Prem Manoj",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126025",
    "name": "Kamareddi Kiran Suresh",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126026",
    "name": "Kadam Rushikesh Ganesh",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126027",
    "name": "Swami Sneha Karbasayya",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126028",
    "name": "Jamadar Saniya Sayyadbasha",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126029",
    "name": "Hiremath Shivanjali Shrishail",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126030",
    "name": "Sakhare Swati Basaveshwar",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126031",
    "name": "Shaikh Afrin Faruk",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126032",
    "name": "Birajdar Naeera Mahiboob",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126033",
    "name": "Birajdar Ganesh Parmeshwar",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126034",
    "name": "Mane Aditya Sunil",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFP126035",
    "name": "Shaikh Ifat Jamir",
    "program": "MCA",
    "group": "G1"
  },
  {
    "prn": "SCFU426001",
    "name": "Yadav Kashmira Rahul",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426002",
    "name": "Mohite Yash Sachin",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426003",
    "name": "Dhumal Aditya Amar",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426004",
    "name": "Bagal Janhavi Vasudev",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426005",
    "name": "Chavan Arnav Prabhakar",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426006",
    "name": "Khatal Shivraj Sharadchandra",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426007",
    "name": "Mohmmad Muzammil Adbul Razzak Maygeri",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426008",
    "name": "Zabiullah Kalinulleh Mangalgiri",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426009",
    "name": "Chitte Iresh Yogesh",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426010",
    "name": "Abhinash Pandhiary",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426011",
    "name": "Dhanshetti Vedant Prashant",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426012",
    "name": "Jadhav Yashashri Shravan",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426013",
    "name": "Tabib Ayan Farooque",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426014",
    "name": "Randive Rohit Sudhakar",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426015",
    "name": "Jadhav varun Shravan",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426016",
    "name": "Patel Tilak Jagdish",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426017",
    "name": "Gaddam Aryan Kashinath",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426018",
    "name": "Ghorpade Dhanraj Veersen",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426019",
    "name": "Kharadi Quddus Murtuz",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426020",
    "name": "Ganiger Sanjana S",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426021",
    "name": "Nadaf Tehreen Nabilal",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426022",
    "name": "Nadaf Iram Ismail",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SCFU426023",
    "name": "Jamadar Abutalha M Rafique",
    "program": "B.Tech. AIML",
    "group": "G2"
  },
  {
    "prn": "SEFU126001",
    "name": "Bogam Aryan Somnath",
    "program": "B.Tech. ECE",
    "group": "G2"
  },
  {
    "prn": "SEFU126002",
    "name": "Mallade Shreya Shrikant",
    "program": "B.Tech. ECE",
    "group": "G2"
  },
  {
    "prn": "SEFU126003",
    "name": "Sherikar Sandesh Shrishail",
    "program": "B.Tech. ECE",
    "group": "G2"
  },
  {
    "prn": "SEFU126004",
    "name": "Gaikwad Anvesh Saklesh",
    "program": "B.Tech. ECE",
    "group": "G2"
  },
  {
    "prn": "SEFU126005",
    "name": "Affan Afaque Ansari",
    "program": "B.Tech. ECE",
    "group": "G2"
  },
  {
    "prn": "SEFU126006",
    "name": "Patil Atharva Ravindra",
    "program": "B.Tech. ECE",
    "group": "G2"
  },
  {
    "prn": "SEFU126007",
    "name": "Nalwar Sumit Basavraj",
    "program": "B.Tech. ECE",
    "group": "G2"
  },
  {
    "prn": "SEFU126008",
    "name": "Kalshetty Samarth Girish",
    "program": "B.Tech. ECE",
    "group": "G2"
  },
  {
    "prn": "SEFU126009",
    "name": "Pawar Aniruddha Pawar",
    "program": "B.Tech. ECE",
    "group": "G2"
  },
  {
    "prn": "SCFU126001",
    "name": "Deshpande Ishvari Anil",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126002",
    "name": "Mareddi Gracia Devputra",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126003",
    "name": "Patil Abhishek Gaurishankar",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126004",
    "name": "Parit Abhishek Shankar",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126005",
    "name": "Kardile Shubham Devidas",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126006",
    "name": "Honparkhe Harshwardhan Dayanand",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126007",
    "name": "Kotmale Pranav Pandurang",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126008",
    "name": "Gaikwad Digviraj Prakash",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126009",
    "name": "Deshpande Shreya Rahul",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126010",
    "name": "Mohammad Abdyl Lateef Furqan",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126011",
    "name": "Gophane Kedar Sashikant",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126012",
    "name": "Rathod Samarth Chandrakant",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126013",
    "name": "Badewale Abuzidan Abdul",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126014",
    "name": "Pandit Atharv Dnyaneshwar",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126015",
    "name": "Chandana Vijay Kaldhone",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126016",
    "name": "Dhaygude Saksham Ulhas",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126017",
    "name": "Patil Harsh Nagraj",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126018",
    "name": "Gaikwad Pruthviraj Sunil",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126019",
    "name": "Vhasure Rohit Ratnkant",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126020",
    "name": "Kamlapure Sunil Harshita",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126021",
    "name": "Bandpatte Prem Bhimashankar",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126022",
    "name": "Horginmath Ganesh Gurushantling",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126023",
    "name": "Panda Karttik Kumar",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126024",
    "name": "Birajdar Mohini Vaijanath",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126025",
    "name": "Patil Arya Laxman",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126026",
    "name": "Bhonge Eklavya Vinod",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126027",
    "name": "Kumthe Sabahat Hussain Fazal Hussain",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126028",
    "name": "Padaliya Shreya Alpesh",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126029",
    "name": "Jadhav Vaibhavi Ramesh",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126030",
    "name": "Jamadar Atharva Neminath",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126031",
    "name": "Malique Rehan Mushtaque ahemed shaikh",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCFU126032",
    "name": "Sambharam Madhavi Shriniwas",
    "program": "B.Tech. CSE",
    "group": "G3"
  },
  {
    "prn": "SCLU326001",
    "name": "Mulla Aatif Nisarahmed",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326002",
    "name": "Sayyed Sahil Sattar",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326003",
    "name": "Upadhye Prasad Shankar",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326004",
    "name": "Jadhav Pratik Pramod",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326005",
    "name": "Karampuri ranveer Dayanand",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326006",
    "name": "Somvanshi Aniket Dashrath",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326007",
    "name": "Inde Samarth Santosh",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326008",
    "name": "Sanade Prajwal Yallappa",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326009",
    "name": "Bisoyi Aditya Krishnachandra",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326010",
    "name": "Hundekar Aditya Prakash",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326011",
    "name": "Dasari Tejas Manohar",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326012",
    "name": "Patil Abhishek Siddhaling",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326013",
    "name": "Khamkar Madhavi Santosh",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326014",
    "name": "Jamadar Mustafa Sabir Husain",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326015",
    "name": "Mandolikar Piyush Prakash",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326016",
    "name": "Abdul Raheman Adbul Sattar Shaikh",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326017",
    "name": "Tumma Gouriprasad Narendra",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326018",
    "name": "Kulkarni Siddhi Prasad",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326019",
    "name": "Kallurkar Yogiraj Mutturaj",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326020",
    "name": "Kadam Sanchita Vyanktesh",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326021",
    "name": "Mittha Prasad Niranjan",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326022",
    "name": "Yengul Shivanand Venugopal",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326023",
    "name": "Nikam hrishikesh Hanmant",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326024",
    "name": "Nadargi Arjun Ganesh",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326025",
    "name": "Kassa Darshan Raju",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326026",
    "name": "Chavan Mahesh Mohanchand",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326027",
    "name": "Samal Naveen Narendra",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326028",
    "name": "Shabdi Awais Imtiyaz",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326029",
    "name": "Bhenki Aakanksha Babasaheb",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326030",
    "name": "Ingale Kaushikkumar Sunilkumar",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326031",
    "name": "Gidde Prathmesh Pradip",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCLU326032",
    "name": "Lad Janhavi Sachin",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G4"
  },
  {
    "prn": "SCFP126036",
    "name": "Gavali Pratiksha Bharat",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126037",
    "name": "Tamboli Saniya Ismail",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126038",
    "name": "Vadaje Harshraj Rahul",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126039",
    "name": "Kota Mallesham Rajesham",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126040",
    "name": "Tamboli Sumera Rajasaheb",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126041",
    "name": "Sathe Virag Amar",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126042",
    "name": "Yadav Priya Santosh",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126043",
    "name": "Mariya Riyaz Ahmed Lokapalli",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126044",
    "name": "Kaif Ismail Kalyani",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126045",
    "name": "Firdous Md.Saleem Shaikh",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126046",
    "name": "Vhasure Sakshi Ratnkant",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126047",
    "name": "Tangsal Mariya Ashfaque",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126048",
    "name": "Mamdyal Vaishnavi Ashwin",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126049",
    "name": "Tiwari Subhi Bal Krishna",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126050",
    "name": "Lavate Sneha Devendra",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126051",
    "name": "Kumar Kalash Santosh",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126052",
    "name": "Sarvade Atharv Manoj",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126053",
    "name": "Jadhav Ajit Yamnurappa",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126054",
    "name": "Gavandi Darshan Basavraj",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126055",
    "name": "Mhnatati Bablu Ramesh",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126056",
    "name": "Matthe Nilesh Ratan",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFP126057",
    "name": "Samal Govardhan Dashrath",
    "program": "MCA",
    "group": "G5"
  },
  {
    "prn": "SCFU126033",
    "name": "Sahoo Pushpdeep Sanjaykumar",
    "program": "B.Tech. CSE",
    "group": "G5"
  },
  {
    "prn": "SCFU126034",
    "name": "Gurav Samarth Shivaji",
    "program": "B.Tech. CSE",
    "group": "G5"
  },
  {
    "prn": "SCFU126035",
    "name": "Chavan Sakshi Sharad",
    "program": "B.Tech. CSE",
    "group": "G5"
  },
  {
    "prn": "SCFU126036",
    "name": "Shirgure Sangmesh Umakant",
    "program": "B.Tech. CSE",
    "group": "G5"
  },
  {
    "prn": "SCFU126037",
    "name": "Wale Shravani Siddharam",
    "program": "B.Tech. CSE",
    "group": "G5"
  },
  {
    "prn": "SCFU126038",
    "name": "Mhetre Prakruti Prabhudas",
    "program": "B.Tech. CSE",
    "group": "G5"
  },
  {
    "prn": "SCLU326033",
    "name": "Hibare Shubham Ranjit",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G5"
  },
  {
    "prn": "SCLU326034",
    "name": "Kulkarni Sanika Abhay",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G5"
  },
  {
    "prn": "SCLU326035",
    "name": "Jakkal Aryan Anand",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G5"
  },
  {
    "prn": "SCLU326036",
    "name": "Deokar Aadesh Vishwasrao",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G5"
  },
  {
    "prn": "SCLU326037",
    "name": "Banajgolkar Ritesh Nilappa",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G5"
  },
  {
    "prn": "SCLU326038",
    "name": "Jamma Atharva Kuber",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G5"
  },
  {
    "prn": "SCLU326039",
    "name": "Hukkeri Nikhil Nagnath",
    "program": "B.Tech. IT-Lateral Entry",
    "group": "G5"
  },
  {
    "prn": "BSFU126001",
    "name": "Mashale Vaibhav Ramchandra",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126002",
    "name": "Choudhary Suraj Sakharam",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126003",
    "name": "Diddi Shruti Nitin",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126004",
    "name": "Phatate Jaywardhan Surendra",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126005",
    "name": "Mhetre Samarth Vijay",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126006",
    "name": "Jagtap Pruthviraj Chandrakant",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126007",
    "name": "Bhaikatti Om Amit",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126008",
    "name": "Bhosale Shital Vitthal",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126009",
    "name": "Chakurkar Chetan Vishal",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126010",
    "name": "Degaonkar Aarya Amar",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126011",
    "name": "Bhosale Onkar Jagannath",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126012",
    "name": "Gidde Shreyash Pradip",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126013",
    "name": "Mahindrakar Sushmitha Manohar",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126014",
    "name": "Rajput Sanchita Rishikaish",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126015",
    "name": "Khade Samyak Anil",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126016",
    "name": "Raut Aonkar Anil",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126017",
    "name": "Mogili Ram Charan Teja",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126018",
    "name": "Virpe Shivam Rajesh",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126019",
    "name": "Chougule Siddhi Amar",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126020",
    "name": "Dhumal Sarthak Atul",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126021",
    "name": "Manya Kumari",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126022",
    "name": "Khandare Tanish Mahadev",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126023",
    "name": "Patel Ganesh Mahesh",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126024",
    "name": "Shinde Dadaso Chandrakant",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126025",
    "name": "Jalanapure Kanhaiyya Mahadev",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126026",
    "name": "Bhonge Shreya Kishor",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126027",
    "name": "Deshmane Sairaj Mahesh",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126028",
    "name": "Yadav Samarth Mahesh",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126029",
    "name": "Kongari Lahari Ramswami",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126030",
    "name": "Andol Omkar Sainath",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126031",
    "name": "Marod Komal Anandsing",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126032",
    "name": "Kattimani Prabhat Deepak",
    "program": "BBA",
    "group": "G6"
  },
  {
    "prn": "BSFU126033",
    "name": "Khatavkar Rudraksh Ganesh",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126034",
    "name": "Pawar Adarsh Kisan",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126035",
    "name": "Andhalkar Vedant Nitin",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126036",
    "name": "Mane Pritam Dattatray",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126037",
    "name": "Shipuje Snehal Shashikant",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126038",
    "name": "Dabi Pratham Sonu",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126039",
    "name": "Karande Sanjivani Laxman",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126040",
    "name": "Chavan Sumit Bharat",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126041",
    "name": "Ghogare Sandesh Nitin",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126042",
    "name": "Salvi John Shalem",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126043",
    "name": "Khan Rehnuma Asgar",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126044",
    "name": "Parve Vaishnavi Kiran",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "BSFU126045",
    "name": "Shirasi Anishka Rekha",
    "program": "BBA",
    "group": "G7"
  },
  {
    "prn": "SELU126001",
    "name": "Salgar Kshiteej Raghvendra",
    "program": "B.Tech. ECE-Lateral Entry",
    "group": "G7"
  },
  {
    "prn": "SELU126002",
    "name": "Swami Onkar Lingayya",
    "program": "B.Tech. ECE-Lateral Entry",
    "group": "G7"
  },
  {
    "prn": "SCFU226001",
    "name": "Deo Tejal Mukund",
    "program": "BCA",
    "group": "G7"
  },
  {
    "prn": "SCFU226002",
    "name": "Peerzade Aasim Abdurrazak",
    "program": "BCA",
    "group": "G7"
  },
  {
    "prn": "SCFU226003",
    "name": "Bhandari Rajswapnil Mallikarjun",
    "program": "BCA",
    "group": "G7"
  },
  {
    "prn": "SCFU226004",
    "name": "Mungapatil Aditya Amar",
    "program": "BCA",
    "group": "G7"
  },
  {
    "prn": "SCFU226005",
    "name": "Bhosale Yogiraj Shahaji",
    "program": "BCA",
    "group": "G7"
  },
  {
    "prn": "SCFU226006",
    "name": "Surve Aniket Lahu",
    "program": "BCA",
    "group": "G7"
  },
  {
    "prn": "SCFU226007",
    "name": "Rodage Basavraj Shantesh",
    "program": "BCA",
    "group": "G7"
  },
  {
    "prn": "SCFU226008",
    "name": "Gund Samarth Manoj",
    "program": "BCA",
    "group": "G7"
  },
  {
    "prn": "SCFU226009",
    "name": "Dustakar Tanishka Santosh",
    "program": "BCA",
    "group": "G7"
  },
  {
    "prn": "SCFU226010",
    "name": "Patil Vishakha Mallinath",
    "program": "BCA",
    "group": "G7"
  },
  {
    "prn": "BSFP126001",
    "name": "Chakote Rasika Rajendra",
    "program": "MBA",
    "group": "G7"
  },
  {
    "prn": "BSFP126002",
    "name": "Bhansali Shruti Abhay",
    "program": "MBA",
    "group": "G7"
  },
  {
    "prn": "BSFP126003",
    "name": "Pujari Manjula Mallappa",
    "program": "MBA",
    "group": "G7"
  },
  {
    "prn": "BSFP126004",
    "name": "Surana Sakshi Shantilal",
    "program": "MBA",
    "group": "G7"
  },
  {
    "prn": "BSFP126005",
    "name": "Ambare Sampada Shrishail",
    "program": "MBA",
    "group": "G7"
  },
  {
    "prn": "BSFP126006",
    "name": "Maykal Shrirnag Vishnu",
    "program": "MBA",
    "group": "G7"
  },
  {
    "prn": "BSFP126007",
    "name": "Deshmukh Digvijay Vinayakrao",
    "program": "MBA",
    "group": "G7"
  },
  {
    "prn": "BSFP126008",
    "name": "Reddy Vasihnavi Vinay",
    "program": "MBA",
    "group": "G7"
  },
  {
    "prn": "BSFP126009",
    "name": "Bhosale Shruti Rajkumar",
    "program": "MBA",
    "group": "G7"
  },
  {
    "prn": "BSFP226001",
    "name": "Mengane Srushti Sunil",
    "program": "MBA Pharma",
    "group": "G8"
  },
  {
    "prn": "BSFP226002",
    "name": "Patu Shashank Satish",
    "program": "MBA Pharma",
    "group": "G8"
  },
  {
    "prn": "BSFP226003",
    "name": "Puranik Vinod Irabasappa",
    "program": "MBA Pharma",
    "group": "G8"
  },
  {
    "prn": "BSFP226004",
    "name": "Jeure Paurnima Chandrashekar",
    "program": "MBA Pharma",
    "group": "G8"
  },
  {
    "prn": "BSFP226005",
    "name": "Takalikar Atharva Dharmraj",
    "program": "MBA Pharma",
    "group": "G8"
  },
  {
    "prn": "BSFP226006",
    "name": "Potdar Shruti Mallikarujun",
    "program": "MBA Pharma",
    "group": "G8"
  },
  {
    "prn": "BSFP226007",
    "name": "Tiwadi Purva Kamalkishor",
    "program": "MBA Pharma",
    "group": "G8"
  },
  {
    "prn": "BSFP226008",
    "name": "Thalange Dhansashree Vishal",
    "program": "MBA Pharma",
    "group": "G8"
  },
  {
    "prn": "BSFP226009",
    "name": "Sonavane Sharayu Dilip",
    "program": "MBA Pharma",
    "group": "G8"
  },
  {
    "prn": "BSFP226010",
    "name": "Kothari Om Rahul",
    "program": "MBA Pharma",
    "group": "G8"
  },
  {
    "prn": "BSFU226001",
    "name": "Bankapur Krutika Dinesh",
    "program": "B.Com.",
    "group": "G8"
  },
  {
    "prn": "BSFU226002",
    "name": "Aadhya Sathish",
    "program": "B.Com.",
    "group": "G8"
  },
  {
    "prn": "SDFU126001",
    "name": "Ranade Anvi Bhushan",
    "program": "B.Des.",
    "group": "G8"
  },
  {
    "prn": "SDFU126002",
    "name": "Zaveriya Sameer Kudle",
    "program": "B.Des.",
    "group": "G8"
  },
  {
    "prn": "SDFU126003",
    "name": "Deshpande Nidhi Atul",
    "program": "B.Des.",
    "group": "G8"
  },
  {
    "prn": "SDFU226001",
    "name": "Pawar Suchita Suresh",
    "program": "B.Sc. Textile",
    "group": "G8"
  },
  {
    "prn": "SDFU226002",
    "name": "Aazam Mohamad Ismail Shaikh",
    "program": "B.Sc. Textile",
    "group": "G8"
  },
  {
    "prn": "SDFU326001",
    "name": "Ghadge Atharva Deepak",
    "program": "B.SC Animation & VFX",
    "group": "G8"
  },
  {
    "prn": "SDFU326002",
    "name": "Gurav Ayush Amar",
    "program": "B.SC Animation & VFX",
    "group": "G8"
  },
  {
    "prn": "SDFU326003",
    "name": "Deshmukh Satyjeet Sanjay",
    "program": "B.SC Animation & VFX",
    "group": "G8"
  },
  {
    "prn": "SDFU326004",
    "name": "Havin Vishwanath Rudrappa",
    "program": "B.SC Animation & VFX",
    "group": "G8"
  },
  {
    "prn": "SDFU326005",
    "name": "Gadgimath Vinayak Ravikanth",
    "program": "B.SC Animation & VFX",
    "group": "G8"
  },
  {
    "prn": "SDFU326006",
    "name": "Trivedi Vishruti Chaitanyabhai",
    "program": "B.SC Animation & VFX",
    "group": "G8"
  },
  {
    "prn": "SDFU326007",
    "name": "Shaikh Ayan Mohiddin",
    "program": "B.SC Animation & VFX",
    "group": "G8"
  },
  {
    "prn": "SDFU326008",
    "name": "Ghongade Varadraje Kishor",
    "program": "B.SC Animation & VFX",
    "group": "G8"
  },
  {
    "prn": "SPFU126001",
    "name": "Birajdar Prathmesh Shrishail",
    "program": "B.Pharm",
    "group": "G8"
  },
  {
    "prn": "SPFU126002",
    "name": "Kambale Adwaita Sangram",
    "program": "B.Pharm",
    "group": "G8"
  },
  {
    "prn": "SPFU126003",
    "name": "Yerwa Shrutika Avinash",
    "program": "B.Pharm",
    "group": "G8"
  }
];

const GROUP_SCHEDULE = {
  "G1": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration Session - I",
      "location": "",
      "useProgramRoom": true
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch / Registration Session - II",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "4:30 PM – 5:15 PM",
      "activity": "Formal Function",
      "location": ""
    },
    {
      "time": "5:30 PM – 6:15 PM",
      "activity": "Cultural Program",
      "location": ""
    }
  ],
  "G2": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration Session - I",
      "location": "",
      "useProgramRoom": true
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch / Registration Session - II",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "4:30 PM – 5:15 PM",
      "activity": "Formal Function",
      "location": ""
    },
    {
      "time": "5:30 PM – 6:15 PM",
      "activity": "Cultural Program",
      "location": ""
    }
  ],
  "G3": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration Session - I",
      "location": "",
      "useProgramRoom": true
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch / Registration Session - II",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "4:30 PM – 5:15 PM",
      "activity": "Formal Function",
      "location": ""
    },
    {
      "time": "5:30 PM – 6:15 PM",
      "activity": "Cultural Program",
      "location": ""
    }
  ],
  "G4": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration Session - I",
      "location": "",
      "useProgramRoom": true
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch / Registration Session - II",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "4:30 PM – 5:15 PM",
      "activity": "Formal Function",
      "location": ""
    },
    {
      "time": "5:30 PM – 6:15 PM",
      "activity": "Cultural Program",
      "location": ""
    }
  ],
  "G5": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration Session - I",
      "location": "",
      "useProgramRoom": true
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch / Registration Session - II",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "4:30 PM – 5:15 PM",
      "activity": "Formal Function",
      "location": ""
    },
    {
      "time": "5:30 PM – 6:15 PM",
      "activity": "Cultural Program",
      "location": ""
    }
  ],
  "G6": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration Session - I",
      "location": "",
      "useProgramRoom": true
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch / Registration Session - II",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "4:30 PM – 5:15 PM",
      "activity": "Formal Function",
      "location": ""
    },
    {
      "time": "5:30 PM – 6:15 PM",
      "activity": "Cultural Program",
      "location": ""
    }
  ],
  "G7": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration Session - I",
      "location": "",
      "useProgramRoom": true
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch / Registration Session - II",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "4:30 PM – 5:15 PM",
      "activity": "Formal Function",
      "location": ""
    },
    {
      "time": "5:30 PM – 6:15 PM",
      "activity": "Cultural Program",
      "location": ""
    }
  ],
  "G8": [
    {
      "time": "10:00 AM – 11:00 AM",
      "activity": "Registration Session - I",
      "location": "",
      "useProgramRoom": true
    },
    {
      "time": "11:15 AM – 12:00 PM",
      "activity": "Citizenship & Responsibility",
      "location": ""
    },
    {
      "time": "12:15 PM – 1:00 PM",
      "activity": "Campus Tour",
      "location": ""
    },
    {
      "time": "1:00 PM – 2:00 PM",
      "activity": "Lunch / Registration Session - II",
      "location": ""
    },
    {
      "time": "2:00 PM – 2:45 PM",
      "activity": "LinkedIn Workshop",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "3:00 PM – 3:45 PM",
      "activity": "Cyber Security",
      "location": "Auditorium (6th Floor)"
    },
    {
      "time": "4:30 PM – 5:15 PM",
      "activity": "Formal Function",
      "location": ""
    },
    {
      "time": "5:30 PM – 6:15 PM",
      "activity": "Cultural Program",
      "location": ""
    }
  ]
};

const ROOM_BY_PROGRAM = {
  "MCA": {
    "student": "Room 219 (2nd Floor)",
    "parent": "Room 213 (2nd Floor)"
  },
  "B.Tech. AIML": {
    "student": "Room 317 (3rd Floor)",
    "parent": "Room 303 (3rd Floor)"
  },
  "B.Tech. ECE": {
    "student": "Room 202 (2nd Floor)",
    "parent": "Room 204 (2nd Floor)"
  },
  "B.Tech. ECE-Lateral Entry": {
    "student": "Room 202 (2nd Floor)",
    "parent": "Room 204 (2nd Floor)"
  },
  "B.Tech. IT-Lateral Entry": {
    "student": "Room 202 (2nd Floor)",
    "parent": "Room 204 (2nd Floor)"
  },
  "B.Tech. CSE": {
    "student": "Room 304 (3rd Floor)",
    "parent": "Room 305 (3rd Floor)"
  },
  "BCA": {
    "student": "Room 306 (3rd Floor)",
    "parent": "Room 307 (3rd Floor)"
  },
  "B.Pharm": {
    "student": "Room 517 (5th Floor)",
    "parent": "Room 518 (5th Floor)"
  },
  "B.Des.": {
    "student": "Room 410 (4th Floor)",
    "parent": "Room 410 (4th Floor)"
  },
  "B.Sc. Textile": {
    "student": "Room 410 (4th Floor)",
    "parent": "Room 410 (4th Floor)"
  },
  "B.SC Animation & VFX": {
    "student": "Room 410 (4th Floor)",
    "parent": "Room 410 (4th Floor)"
  },
  "MBA": {
    "student": "Room 501 (5th Floor)",
    "parent": "Room 502 (5th Floor)"
  },
  "MBA Pharma": {
    "student": "Room 501 (5th Floor)",
    "parent": "Room 502 (5th Floor)"
  },
  "BBA": {
    "student": "Room 510 (5th Floor)",
    "parent": "Room 511 (5th Floor)"
  },
  "B.Com.": {
    "student": "Room 515 (5th Floor)",
    "parent": "Room 515 (5th Floor)"
  }
};
