// Translations for UI text and for the schedule/room content generated by
// generate_data.py. The schedule/room strings baked into data.js are always
// English (that's what generate_data.py writes), so ACTIVITY_TRANSLATIONS
// and LOCATION_TRANSLATIONS translate by looking up that exact English text.
// If an activity name or room format changes in generate_data.py, update the
// matching entry here too — anything missing just falls back to English.
(function (global) {
  "use strict";

  var DEFAULT_LANG = "en";
  var STORAGE_KEY = "orientationLang";

  var LANGUAGES = [
    { code: "en", label: "English" },
    { code: "mr", label: "मराठी" },
    { code: "hi", label: "हिंदी" }
  ];

  var UI_TEXT = {
    en: {
      titleSuffix: " — Orientation",
      brandSubtitle: "Student Orientation Portal",
      heroTitle: "Find Your Orientation Group",
      heroSubtitle: "Enter your <strong>PRN</strong> or <strong>Name</strong> to see your group, room and today's schedule.",
      searchPlaceholder: "Enter PRN or Name (e.g. SCFP126001 or Perala Nikita Ramkrishana)",
      searchAriaLabel: "Search by PRN or Name",
      clearAriaLabel: "Clear search",
      searchButton: "Search",
      groupLabel: "Group",
      prnLabel: "PRN",
      programLabel: "Program",
      parentSeatingLabel: "Parent Seating (10:00–11:00 AM)",
      todaysScheduleTitle: "Today's Schedule",
      forParentsTitle: "For Parents",
      idleHintText: "Your details will appear here once you search.",
      footerText: "Having trouble finding your details? Please visit the Registration Desk for assistance.",
      promptEnterQuery: "Please enter your PRN or Name to search.",
      matchedStudents: "{count} students matched “{query}”. Select yours from the list below.",
      noStudentFound: "No student found for “{query}”. Please check the spelling, or try your PRN instead. If the issue persists, visit the Registration Desk.",
      moreMatchesOne: "+{count} more match — type more of the name or PRN to narrow it down",
      moreMatchesOther: "+{count} more matches — type more of the name or PRN to narrow it down",
      scheduleNotAvailable: "Schedule not available for your group yet. Please check with the Registration Desk.",
      parentSessionsAnnounced: "Parent session details will be announced at Registration.",
      welcomeMessage: "Welcome, {name}! We're delighted to have you join {institution}. Head to your Group {group} activities and have a wonderful orientation day!",
      checkRegistrationDesk: "Check Registration Desk",
      languageLabel: "Language",
      saveImageButton: "Save as Image",
      saveImageButtonBusy: "Preparing image…",
      saveImageError: "Couldn't save the image. Please try again or take a screenshot instead."
    },
    mr: {
      titleSuffix: " — ओरिएंटेशन",
      brandSubtitle: "विद्यार्थी ओरिएंटेशन पोर्टल",
      heroTitle: "तुमचा ओरिएंटेशन गट शोधा",
      heroSubtitle: "तुमचा गट, खोली आणि आजचे वेळापत्रक पाहण्यासाठी तुमचा <strong>PRN</strong> किंवा <strong>नाव</strong> टाका.",
      searchPlaceholder: "PRN किंवा नाव टाका (उदा. SCFP126001 किंवा Perala Nikita Ramkrishana)",
      searchAriaLabel: "PRN किंवा नावाने शोधा",
      clearAriaLabel: "शोध साफ करा",
      searchButton: "शोधा",
      groupLabel: "गट",
      prnLabel: "PRN",
      programLabel: "अभ्यासक्रम",
      parentSeatingLabel: "पालक बैठक व्यवस्था (10:00–11:00 AM)",
      todaysScheduleTitle: "आजचे वेळापत्रक",
      forParentsTitle: "पालकांसाठी",
      idleHintText: "शोधल्यानंतर तुमचा तपशील येथे दिसेल.",
      footerText: "तुमचा तपशील शोधण्यात अडचण येत आहे? कृपया मदतीसाठी नोंदणी कक्षाला भेट द्या.",
      promptEnterQuery: "कृपया शोधण्यासाठी तुमचा PRN किंवा नाव टाका.",
      matchedStudents: "“{query}” साठी {count} विद्यार्थी जुळले. खालील यादीतून तुमचे नाव निवडा.",
      noStudentFound: "“{query}” साठी कोणताही विद्यार्थी सापडला नाही. कृपया शब्दलेखन तपासा किंवा त्याऐवजी तुमचा PRN वापरून पहा. समस्या कायम राहिल्यास, नोंदणी कक्षाला भेट द्या.",
      moreMatchesOne: "+{count} अधिक जुळणी — नाव किंवा PRN आणखी टाइप करून यादी मर्यादित करा",
      moreMatchesOther: "+{count} अधिक जुळण्या — नाव किंवा PRN आणखी टाइप करून यादी मर्यादित करा",
      scheduleNotAvailable: "तुमच्या गटासाठी वेळापत्रक अद्याप उपलब्ध नाही. कृपया नोंदणी कक्षाशी संपर्क साधा.",
      parentSessionsAnnounced: "पालक सत्राचा तपशील नोंदणीच्या वेळी जाहीर केला जाईल.",
      welcomeMessage: "स्वागत आहे, {name}! तुम्ही {institution} मध्ये सामील झाल्याचा आम्हाला आनंद आहे. तुमच्या गट {group} च्या उपक्रमांकडे जा आणि ओरिएंटेशन दिवसाचा आनंद घ्या!",
      checkRegistrationDesk: "नोंदणी कक्षाशी संपर्क साधा",
      languageLabel: "भाषा",
      saveImageButton: "प्रतिमा म्हणून जतन करा",
      saveImageButtonBusy: "प्रतिमा तयार करत आहे…",
      saveImageError: "प्रतिमा जतन करता आली नाही. कृपया पुन्हा प्रयत्न करा किंवा स्क्रीनशॉट घ्या."
    },
    hi: {
      titleSuffix: " — ओरिएंटेशन",
      brandSubtitle: "छात्र ओरिएंटेशन पोर्टल",
      heroTitle: "अपना ओरिएंटेशन ग्रुप खोजें",
      heroSubtitle: "अपना ग्रुप, कमरा और आज का कार्यक्रम देखने के लिए अपना <strong>PRN</strong> या <strong>नाम</strong> दर्ज करें।",
      searchPlaceholder: "PRN या नाम दर्ज करें (उदा. SCFP126001 या Perala Nikita Ramkrishana)",
      searchAriaLabel: "PRN या नाम से खोजें",
      clearAriaLabel: "खोज साफ़ करें",
      searchButton: "खोजें",
      groupLabel: "ग्रुप",
      prnLabel: "PRN",
      programLabel: "पाठ्यक्रम",
      parentSeatingLabel: "अभिभावक बैठक व्यवस्था (10:00–11:00 AM)",
      todaysScheduleTitle: "आज का कार्यक्रम",
      forParentsTitle: "अभिभावकों के लिए",
      idleHintText: "खोजने के बाद आपका विवरण यहाँ दिखाई देगा।",
      footerText: "अपना विवरण खोजने में समस्या हो रही है? कृपया सहायता के लिए पंजीकरण डेस्क पर जाएँ।",
      promptEnterQuery: "कृपया खोजने के लिए अपना PRN या नाम दर्ज करें।",
      matchedStudents: "“{query}” के लिए {count} छात्र मिले। नीचे दी गई सूची में से अपना चुनें।",
      noStudentFound: "“{query}” के लिए कोई छात्र नहीं मिला। कृपया वर्तनी जाँचें, या इसके बजाय अपना PRN आज़माएँ। समस्या बने रहने पर, पंजीकरण डेस्क पर जाएँ।",
      moreMatchesOne: "+{count} और मेल — सूची सीमित करने के लिए नाम या PRN में और टाइप करें",
      moreMatchesOther: "+{count} और मेल — सूची सीमित करने के लिए नाम या PRN में और टाइप करें",
      scheduleNotAvailable: "आपके ग्रुप के लिए कार्यक्रम अभी उपलब्ध नहीं है। कृपया पंजीकरण डेस्क से संपर्क करें।",
      parentSessionsAnnounced: "अभिभावक सत्र का विवरण पंजीकरण के समय बताया जाएगा।",
      welcomeMessage: "स्वागत है, {name}! हमें खुशी है कि आप {institution} से जुड़े। अपने ग्रुप {group} की गतिविधियों में शामिल हों और ओरिएंटेशन दिवस का आनंद लें!",
      checkRegistrationDesk: "पंजीकरण डेस्क से जाँच करें",
      languageLabel: "भाषा",
      saveImageButton: "छवि के रूप में सहेजें",
      saveImageButtonBusy: "छवि तैयार हो रही है…",
      saveImageError: "छवि सहेजी नहीं जा सकी। कृपया पुनः प्रयास करें या स्क्रीनशॉट लें।"
    }
  };

  // The registered institution name is transliterated (not a literal
  // translation) for the Devanagari-script languages; English uses whatever
  // INSTITUTION_NAME data.js provides, so it stays in sync with generate_data.py.
  var INSTITUTION_NAMES = {
    mr: "एमआयटी विश्वप्रयाग विद्यापीठ, सोलापूर",
    hi: "एमआईटी विश्वप्रयाग विश्वविद्यालय, सोलापुर"
  };

  var FALLBACK_INSTITUTION = {
    en: "our campus",
    mr: "आमचे कॅम्पस",
    hi: "हमारा परिसर"
  };

  var ACTIVITY_TRANSLATIONS = {
    "Registration Session - I": { mr: "नोंदणी सत्र - I", hi: "पंजीकरण सत्र - I" },
    "Registration Session - II": { mr: "नोंदणी सत्र - II", hi: "पंजीकरण सत्र - II" },
    "LinkedIn Workshop": { mr: "LinkedIn कार्यशाळा", hi: "LinkedIn कार्यशाला" },
    "Cyber Security": { mr: "सायबर सुरक्षा", hi: "साइबर सुरक्षा" },
    "Lunch / Registration Session - II": { mr: "जेवण / नोंदणी सत्र - II", hi: "भोजन / पंजीकरण सत्र - II" },
    "Citizenship & Responsibility": { mr: "नागरिकत्व आणि जबाबदारी", hi: "नागरिकता और जिम्मेदारी" },
    "Campus Tour": { mr: "कॅम्पस फेरफटका", hi: "कैंपस भ्रमण" },
    "Formal Function": { mr: "औपचारिक कार्यक्रम", hi: "औपचारिक कार्यक्रम" },
    "Cultural Program": { mr: "सांस्कृतिक कार्यक्रम", hi: "सांस्कृतिक कार्यक्रम" },
    "Parenting Gen-Z": { mr: "Gen-Z चे पालकत्व", hi: "Gen-Z की परवरिश" },
    "Snacks": { mr: "अल्पोपाहार", hi: "जलपान" }
  };

  var LOCATION_TRANSLATIONS = {
    "Auditorium (6th Floor)": { mr: "सभागृह (6वा मजला)", hi: "सभागार (छठी मंजिल)" },
    "Seminar Hall (1st Floor)": { mr: "सेमिनार हॉल (1ला मजला)", hi: "सेमिनार हॉल (पहली मंजिल)" },
    "University Main Building (Ground Floor) – Report to the venue 10 mins before.": {
      mr: "विद्यापीठ मुख्य इमारत (तळमजला) – कार्यक्रमाच्या 10 मिनिटे आधी उपस्थित रहा.",
      hi: "विश्वविद्यालय मुख्य भवन (भूतल) – कार्यक्रम स्थल पर 10 मिनट पहले पहुंचें."
    },
    "In front of University Main Building – Report to the venue 10 mins before.": {
      mr: "विद्यापीठ मुख्य इमारतीसमोर – कार्यक्रमाच्या 10 मिनिटे आधी उपस्थित रहा.",
      hi: "विश्वविद्यालय मुख्य भवन के सामने – कार्यक्रम स्थल पर 10 मिनट पहले पहुंचें."
    },
    "In front of University Main Building": {
      mr: "विद्यापीठ मुख्य इमारतीसमोर",
      hi: "विश्वविद्यालय मुख्य भवन के सामने"
    },
    "Tensile Structure (besides Canteen)": {
      mr: "टेन्साइल स्ट्रक्चर (कॅन्टीनजवळ)",
      hi: "टेंसाइल स्ट्रक्चर (कैंटीन के पास)"
    }
  };

  var FLOOR_ORDINALS = {
    mr: { 1: "पहिला", 2: "दुसरा", 3: "तिसरा", 4: "चौथा", 5: "पाचवा", 6: "सहावा", 7: "सातवा", 8: "आठवा", 9: "नववा" },
    hi: { 1: "पहली", 2: "दूसरी", 3: "तीसरी", 4: "चौथी", 5: "पांचवीं", 6: "छठी", 7: "सातवीं", 8: "आठवीं", 9: "नौवीं" }
  };

  var ROOM_WORD = { mr: "खोली", hi: "कमरा" };
  var FLOOR_WORD = { mr: "मजला", hi: "मंजिल" };

  function getLang() {
    try {
      var saved = global.localStorage.getItem(STORAGE_KEY);
      if (saved && UI_TEXT[saved]) return saved;
    } catch (e) {
      // localStorage unavailable (private mode, etc.) — fall through to default.
    }
    return DEFAULT_LANG;
  }

  function setLang(lang) {
    try {
      global.localStorage.setItem(STORAGE_KEY, lang);
    } catch (e) {
      // Ignore — language just won't persist across visits.
    }
  }

  function format(str, params) {
    if (!params) return str;
    return str.replace(/\{(\w+)\}/g, function (match, key) {
      return Object.prototype.hasOwnProperty.call(params, key) ? params[key] : match;
    });
  }

  function t(lang, key, params) {
    var dict = UI_TEXT[lang] || UI_TEXT[DEFAULT_LANG];
    var text = (dict && dict[key] != null) ? dict[key] : UI_TEXT[DEFAULT_LANG][key] || key;
    return format(text, params);
  }

  function translateActivity(text, lang) {
    if (lang === DEFAULT_LANG || !text) return text;
    var entry = ACTIVITY_TRANSLATIONS[text];
    return (entry && entry[lang]) || text;
  }

  function translateLocation(text, lang) {
    if (lang === DEFAULT_LANG || !text) return text;

    var fixed = LOCATION_TRANSLATIONS[text];
    if (fixed && fixed[lang]) return fixed[lang];

    var match = /^Room (\d+) \((\d)(?:st|nd|rd|th) Floor\)$/.exec(text);
    if (match) {
      var ordinal = FLOOR_ORDINALS[lang] && FLOOR_ORDINALS[lang][parseInt(match[2], 10)];
      if (ordinal) {
        return ROOM_WORD[lang] + " " + match[1] + " (" + ordinal + " " + FLOOR_WORD[lang] + ")";
      }
    }

    return text;
  }

  function getInstitutionName(lang, englishName) {
    if (lang !== DEFAULT_LANG && INSTITUTION_NAMES[lang]) return INSTITUTION_NAMES[lang];
    return englishName || FALLBACK_INSTITUTION[lang] || FALLBACK_INSTITUTION[DEFAULT_LANG];
  }

  global.I18N = {
    LANGUAGES: LANGUAGES,
    DEFAULT_LANG: DEFAULT_LANG,
    getLang: getLang,
    setLang: setLang,
    t: t,
    translateActivity: translateActivity,
    translateLocation: translateLocation,
    getInstitutionName: getInstitutionName
  };
})(window);
